#====================================================
##   _   ____  ______  _  _______  _  ___________ 
##  | | / / / / / __ \/ |/ / ___/ / |/ / ___/ __ \
##  | |/ / /_/ / /_/ /    / (_ / /    / (_ / /_/ /
##  |___/\____/\____/_/|_/\___/ /_/|_/\___/\____/ 
#====================================================

#################
### AUTOSTART ###
#################
# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = waybar
exec-once = swaync
exec-once = swaybg -i ~/.cache/current_wallpaper -m fill
exec-once = hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = gnome-keyring-daemon --start --components=secrets

exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# Reset Night Light state on startup for consistency
exec-once = rm -f /tmp/night_light_state && pkill wlsunset

# Enable Fcitx5 daemon
exec-once = fcitx5 -d
exec-once = udiskie
