#====================================================
##   _   ____  ______  _  _______  _  ___________ 
##  | | / / / / / __ \/ |/ / ___/ / |/ / ___/ __ \
##  | |/ / /_/ / /_/ /    / (_ / /    / (_ / /_/ /
##  |___/\____/\____/_/|_/\___/ /_/|_/\___/\____/ 
#====================================================

#############
### INPUT ###
#############
# https://wiki.hypr.land/Configuring/Variables/#input

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0.5 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

cursor {
    inactive_timeout = 5
    hide_on_key_press = true
    no_hardware_cursors = false
    enable_hyprcursor = true
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = 0.5
}
