#====================================================
##   _   ____  ______  _  _______  _  ___________ 
##  | | / / / / / __ \/ |/ / ___/ / |/ / ___/ __ \
##  | |/ / /_/ / /_/ /    / (_ / /    / (_ / /_/ /
##  |___/\____/\____/_/|_/\___/ /_/|_/\___/\____/ 
#====================================================

################
### MONITORS ###
################
# See https://wiki.hypr.land/Configuring/Monitors/

monitor = , 1920x1080@60, auto, 1.0

# monitor = ,preferred,auto,1.1
# monitor=,1920x1080@75,auto,auto
